name = "MicrosimAPI"
uuid = "61038afa-740f-4e54-9cae-22f264703afd"
authors = ["Graham Stark"]
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ScottishTaxBenefitModel = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
ScottishTaxBenefitModel = {url = "https://github.com/grahamstark/ScottishTaxBenefitModel.jl"}

[compat]
DataStructures = "0,1"
Dates = "1,2"
HTTP = "1"
JSON3 = "1"
LoggingExtras = "1,2"
Mux = "1"
Observables = "0,1"
Oxygen = "1,2"
Parameters = "0,1"
Random = "1,2"
Reexport = "1,2"
ScottishTaxBenefitModel = "0,1"
StructTypes = "1,2"
UUIDs = "1,2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[preferences.ScottishTaxBenefitModel]
do_marginal_rates = true
do_replacement_rates = true
dump_frames = false
included_data_years = [2019, 2021, 2022, 2023]
local-artifact_server_url_unix = "file:///mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_windows = "file:///c:/data/"
lower_multiple = 0.65
means_tested_routing = "uc_full"
output_dir = "output"
requested_threads = 6
target_bc_income = "bhc_hh"
to_q = 3
to_y = 2025
upper_multiple = 3.7
weighting_relative_to_ons_weights = true
weighting_strategy = "use_runtime_computed_weights"